development: &default
  adapter: postgresql
  encoding: unicode
  database: torkel_development
  username: elabs
  password:

test:
  <<: *default
  database: torkel_test

production:
  <<: *default
  database: torkel_production
