development: &default
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  database: torkel_development
  username: elabs
  password: elabs

test:
  <<: *default
  database: torkel_test

production:
  <<: *default
  database: torkel_production
